### PR TITLE
Support for new AI/book_style/access controls constructors

### PR DESCRIPTION
**Pull request by OrbitalPeriod**
Added the constructors for the new API data from pixiv, it throws an except if they're not there.

### CODE REVIEW

**Comment by azuline** [comment]
doesn't look like the params are used after being passed in, should they be stored on the object instance?

**Comment by OrbitalPeriod** [comment]
I suppose they should be stored on the object instance, I can see them being useful.

**Comment by OrbitalPeriod** [comment]
I couldnt figure out how to make changes to a pull request (im new to this github thing). Could you make the changes?

**Review by azuline — APPROVED** [review]

**Comment by azuline** [comment]
03c5292216cba26a50c460fc5f1ed756fb54a571 merged with squashed commit

**Pull request closed without merging**
